name: Lint
on:
  push:
    branches:
        - 'main'
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
      - 'Makefile'
      - '.github/workflows/lint.yml'
    branches:
      - 'main'

jobs:
  golangci-lint:
    name: golangci lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          workdir: management
          go_version_file: "go.mod"
